#CHEVEZ VASQUEZ MARIA DE LOURDES
# Software
# #Tercer semestre

#Ejercicio 13
#Elabore pseudocódigo para el caso en que se desean 
#escribir los números del 1 al 100.

class Tarea13:
    def __init__ (self):
        pass
    def Variables(self):
        print("_______________________________________")
        print("numeros hasta el 100 con While")
        i=1
        while i <=100:
            print(i)
            i=i+1
                       
        print("_______________________________________")
        input("enter para salir") 
        
resultado = Tarea13()
resultado.Variables()